/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as FinalsRouteImport } from './routes/finals'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DefiRouteImport } from './routes/defi'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiFeedIndexRouteImport } from './routes/api/feed/index'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram/webhook'
import { Route as ApiTelegramPrepareShareRouteImport } from './routes/api/telegram/prepare-share'
import { Route as ApiSwapStatusRouteImport } from './routes/api/swap/status'
import { Route as ApiSwapQuoteRouteImport } from './routes/api/swap/quote'
import { Route as ApiSwapPriceRouteImport } from './routes/api/swap/price'
import { Route as ApiSponsorEligibilityRouteImport } from './routes/api/sponsor/eligibility'
import { Route as ApiSocialVerifyRouteImport } from './routes/api/social/verify'
import { Route as ApiSocialStatusRouteImport } from './routes/api/social/status'
import { Route as ApiPredictionsHistoryRouteImport } from './routes/api/predictions/history'
import { Route as ApiMarketingXPostRouteImport } from './routes/api/marketing/x-post'
import { Route as ApiFarcasterCastRouteImport } from './routes/api/farcaster/cast'
import { Route as ApiAuthXStartRouteImport } from './routes/api/auth/x/start'
import { Route as ApiAuthXCallbackRouteImport } from './routes/api/auth/x/callback'
import { Route as ApiAuthWorldVerifyRouteImport } from './routes/api/auth/world/verify'
import { Route as ApiAuthWorldStartRouteImport } from './routes/api/auth/world/start'
import { Route as ApiAuthTelegramVerifyRouteImport } from './routes/api/auth/telegram/verify'
import { Route as ApiAuthFarcasterVerifyRouteImport } from './routes/api/auth/farcaster/verify'
import { Route as ApiAgentsPepeTickRouteImport } from './routes/api/agents/pepe/tick'
import { Route as ApiAgentsPepeApproveRouteImport } from './routes/api/agents/pepe/approve'
import { Route as ApiAgentsLuckTickRouteImport } from './routes/api/agents/luck/tick'
import { Route as ApiAgentsLuckApproveRouteImport } from './routes/api/agents/luck/approve'
import { Route as ApiAgentsCultureOpsTickRouteImport } from './routes/api/agents/culture-ops/tick'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalsRoute = FinalsRouteImport.update({
  id: '/finals',
  path: '/finals',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DefiRoute = DefiRouteImport.update({
  id: '/defi',
  path: '/defi',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedIndexRoute = ApiFeedIndexRouteImport.update({
  id: '/api/feed/',
  path: '/api/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramPrepareShareRoute = ApiTelegramPrepareShareRouteImport.update({
  id: '/api/telegram/prepare-share',
  path: '/api/telegram/prepare-share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwapStatusRoute = ApiSwapStatusRouteImport.update({
  id: '/api/swap/status',
  path: '/api/swap/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwapQuoteRoute = ApiSwapQuoteRouteImport.update({
  id: '/api/swap/quote',
  path: '/api/swap/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwapPriceRoute = ApiSwapPriceRouteImport.update({
  id: '/api/swap/price',
  path: '/api/swap/price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSponsorEligibilityRoute = ApiSponsorEligibilityRouteImport.update({
  id: '/api/sponsor/eligibility',
  path: '/api/sponsor/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialVerifyRoute = ApiSocialVerifyRouteImport.update({
  id: '/api/social/verify',
  path: '/api/social/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialStatusRoute = ApiSocialStatusRouteImport.update({
  id: '/api/social/status',
  path: '/api/social/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictionsHistoryRoute = ApiPredictionsHistoryRouteImport.update({
  id: '/api/predictions/history',
  path: '/api/predictions/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketingXPostRoute = ApiMarketingXPostRouteImport.update({
  id: '/api/marketing/x-post',
  path: '/api/marketing/x-post',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFarcasterCastRoute = ApiFarcasterCastRouteImport.update({
  id: '/api/farcaster/cast',
  path: '/api/farcaster/cast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthXStartRoute = ApiAuthXStartRouteImport.update({
  id: '/api/auth/x/start',
  path: '/api/auth/x/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthXCallbackRoute = ApiAuthXCallbackRouteImport.update({
  id: '/api/auth/x/callback',
  path: '/api/auth/x/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthWorldVerifyRoute = ApiAuthWorldVerifyRouteImport.update({
  id: '/api/auth/world/verify',
  path: '/api/auth/world/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthWorldStartRoute = ApiAuthWorldStartRouteImport.update({
  id: '/api/auth/world/start',
  path: '/api/auth/world/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTelegramVerifyRoute = ApiAuthTelegramVerifyRouteImport.update({
  id: '/api/auth/telegram/verify',
  path: '/api/auth/telegram/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthFarcasterVerifyRoute = ApiAuthFarcasterVerifyRouteImport.update({
  id: '/api/auth/farcaster/verify',
  path: '/api/auth/farcaster/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsPepeTickRoute = ApiAgentsPepeTickRouteImport.update({
  id: '/api/agents/pepe/tick',
  path: '/api/agents/pepe/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsPepeApproveRoute = ApiAgentsPepeApproveRouteImport.update({
  id: '/api/agents/pepe/approve',
  path: '/api/agents/pepe/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsLuckTickRoute = ApiAgentsLuckTickRouteImport.update({
  id: '/api/agents/luck/tick',
  path: '/api/agents/luck/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsLuckApproveRoute = ApiAgentsLuckApproveRouteImport.update({
  id: '/api/agents/luck/approve',
  path: '/api/agents/luck/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsCultureOpsTickRoute = ApiAgentsCultureOpsTickRouteImport.update({
  id: '/api/agents/culture-ops/tick',
  path: '/api/agents/culture-ops/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/defi': typeof DefiRoute
  '/feed': typeof FeedRoute
  '/finals': typeof FinalsRoute
  '/imprint': typeof ImprintRoute
  '/labs': typeof LabsRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/proof': typeof ProofRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/farcaster/cast': typeof ApiFarcasterCastRoute
  '/api/marketing/x-post': typeof ApiMarketingXPostRoute
  '/api/predictions/history': typeof ApiPredictionsHistoryRoute
  '/api/social/status': typeof ApiSocialStatusRoute
  '/api/social/verify': typeof ApiSocialVerifyRoute
  '/api/sponsor/eligibility': typeof ApiSponsorEligibilityRoute
  '/api/swap/price': typeof ApiSwapPriceRoute
  '/api/swap/quote': typeof ApiSwapQuoteRoute
  '/api/swap/status': typeof ApiSwapStatusRoute
  '/api/telegram/prepare-share': typeof ApiTelegramPrepareShareRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/feed/': typeof ApiFeedIndexRoute
  '/api/agents/culture-ops/tick': typeof ApiAgentsCultureOpsTickRoute
  '/api/agents/luck/approve': typeof ApiAgentsLuckApproveRoute
  '/api/agents/luck/tick': typeof ApiAgentsLuckTickRoute
  '/api/agents/pepe/approve': typeof ApiAgentsPepeApproveRoute
  '/api/agents/pepe/tick': typeof ApiAgentsPepeTickRoute
  '/api/auth/farcaster/verify': typeof ApiAuthFarcasterVerifyRoute
  '/api/auth/telegram/verify': typeof ApiAuthTelegramVerifyRoute
  '/api/auth/world/start': typeof ApiAuthWorldStartRoute
  '/api/auth/world/verify': typeof ApiAuthWorldVerifyRoute
  '/api/auth/x/callback': typeof ApiAuthXCallbackRoute
  '/api/auth/x/start': typeof ApiAuthXStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/defi': typeof DefiRoute
  '/feed': typeof FeedRoute
  '/finals': typeof FinalsRoute
  '/imprint': typeof ImprintRoute
  '/labs': typeof LabsRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/proof': typeof ProofRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/api/farcaster/cast': typeof ApiFarcasterCastRoute
  '/api/marketing/x-post': typeof ApiMarketingXPostRoute
  '/api/predictions/history': typeof ApiPredictionsHistoryRoute
  '/api/social/status': typeof ApiSocialStatusRoute
  '/api/social/verify': typeof ApiSocialVerifyRoute
  '/api/sponsor/eligibility': typeof ApiSponsorEligibilityRoute
  '/api/swap/price': typeof ApiSwapPriceRoute
  '/api/swap/quote': typeof ApiSwapQuoteRoute
  '/api/swap/status': typeof ApiSwapStatusRoute
  '/api/telegram/prepare-share': typeof ApiTelegramPrepareShareRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/feed': typeof ApiFeedIndexRoute
  '/api/agents/culture-ops/tick': typeof ApiAgentsCultureOpsTickRoute
  '/api/agents/luck/approve': typeof ApiAgentsLuckApproveRoute
  '/api/agents/luck/tick': typeof ApiAgentsLuckTickRoute
  '/api/agents/pepe/approve': typeof ApiAgentsPepeApproveRoute
  '/api/agents/pepe/tick': typeof ApiAgentsPepeTickRoute
  '/api/auth/farcaster/verify': typeof ApiAuthFarcasterVerifyRoute
  '/api/auth/telegram/verify': typeof ApiAuthTelegramVerifyRoute
  '/api/auth/world/start': typeof ApiAuthWorldStartRoute
  '/api/auth/world/verify': typeof ApiAuthWorldVerifyRoute
  '/api/auth/x/callback': typeof ApiAuthXCallbackRoute
  '/api/auth/x/start': typeof ApiAuthXStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/defi': typeof DefiRoute
  '/feed': typeof FeedRoute
  '/finals': typeof FinalsRoute
  '/imprint': typeof ImprintRoute
  '/labs': typeof LabsRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/proof': typeof ProofRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/farcaster/cast': typeof ApiFarcasterCastRoute
  '/api/marketing/x-post': typeof ApiMarketingXPostRoute
  '/api/predictions/history': typeof ApiPredictionsHistoryRoute
  '/api/social/status': typeof ApiSocialStatusRoute
  '/api/social/verify': typeof ApiSocialVerifyRoute
  '/api/sponsor/eligibility': typeof ApiSponsorEligibilityRoute
  '/api/swap/price': typeof ApiSwapPriceRoute
  '/api/swap/quote': typeof ApiSwapQuoteRoute
  '/api/swap/status': typeof ApiSwapStatusRoute
  '/api/telegram/prepare-share': typeof ApiTelegramPrepareShareRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/feed/': typeof ApiFeedIndexRoute
  '/api/agents/culture-ops/tick': typeof ApiAgentsCultureOpsTickRoute
  '/api/agents/luck/approve': typeof ApiAgentsLuckApproveRoute
  '/api/agents/luck/tick': typeof ApiAgentsLuckTickRoute
  '/api/agents/pepe/approve': typeof ApiAgentsPepeApproveRoute
  '/api/agents/pepe/tick': typeof ApiAgentsPepeTickRoute
  '/api/auth/farcaster/verify': typeof ApiAuthFarcasterVerifyRoute
  '/api/auth/telegram/verify': typeof ApiAuthTelegramVerifyRoute
  '/api/auth/world/start': typeof ApiAuthWorldStartRoute
  '/api/auth/world/verify': typeof ApiAuthWorldVerifyRoute
  '/api/auth/x/callback': typeof ApiAuthXCallbackRoute
  '/api/auth/x/start': typeof ApiAuthXStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/defi'
    | '/feed'
    | '/finals'
    | '/imprint'
    | '/labs'
    | '/partners'
    | '/privacy'
    | '/profile'
    | '/proof'
    | '/terms'
    | '/blog/$slug'
    | '/blog/'
    | '/api/farcaster/cast'
    | '/api/marketing/x-post'
    | '/api/predictions/history'
    | '/api/social/status'
    | '/api/social/verify'
    | '/api/sponsor/eligibility'
    | '/api/swap/price'
    | '/api/swap/quote'
    | '/api/swap/status'
    | '/api/telegram/prepare-share'
    | '/api/telegram/webhook'
    | '/api/feed/'
    | '/api/agents/culture-ops/tick'
    | '/api/agents/luck/approve'
    | '/api/agents/luck/tick'
    | '/api/agents/pepe/approve'
    | '/api/agents/pepe/tick'
    | '/api/auth/farcaster/verify'
    | '/api/auth/telegram/verify'
    | '/api/auth/world/start'
    | '/api/auth/world/verify'
    | '/api/auth/x/callback'
    | '/api/auth/x/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/defi'
    | '/feed'
    | '/finals'
    | '/imprint'
    | '/labs'
    | '/partners'
    | '/privacy'
    | '/profile'
    | '/proof'
    | '/terms'
    | '/blog/$slug'
    | '/blog'
    | '/api/farcaster/cast'
    | '/api/marketing/x-post'
    | '/api/predictions/history'
    | '/api/social/status'
    | '/api/social/verify'
    | '/api/sponsor/eligibility'
    | '/api/swap/price'
    | '/api/swap/quote'
    | '/api/swap/status'
    | '/api/telegram/prepare-share'
    | '/api/telegram/webhook'
    | '/api/feed'
    | '/api/agents/culture-ops/tick'
    | '/api/agents/luck/approve'
    | '/api/agents/luck/tick'
    | '/api/agents/pepe/approve'
    | '/api/agents/pepe/tick'
    | '/api/auth/farcaster/verify'
    | '/api/auth/telegram/verify'
    | '/api/auth/world/start'
    | '/api/auth/world/verify'
    | '/api/auth/x/callback'
    | '/api/auth/x/start'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/defi'
    | '/feed'
    | '/finals'
    | '/imprint'
    | '/labs'
    | '/partners'
    | '/privacy'
    | '/profile'
    | '/proof'
    | '/terms'
    | '/blog/$slug'
    | '/blog/'
    | '/api/farcaster/cast'
    | '/api/marketing/x-post'
    | '/api/predictions/history'
    | '/api/social/status'
    | '/api/social/verify'
    | '/api/sponsor/eligibility'
    | '/api/swap/price'
    | '/api/swap/quote'
    | '/api/swap/status'
    | '/api/telegram/prepare-share'
    | '/api/telegram/webhook'
    | '/api/feed/'
    | '/api/agents/culture-ops/tick'
    | '/api/agents/luck/approve'
    | '/api/agents/luck/tick'
    | '/api/agents/pepe/approve'
    | '/api/agents/pepe/tick'
    | '/api/auth/farcaster/verify'
    | '/api/auth/telegram/verify'
    | '/api/auth/world/start'
    | '/api/auth/world/verify'
    | '/api/auth/x/callback'
    | '/api/auth/x/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DefiRoute: typeof DefiRoute
  FeedRoute: typeof FeedRoute
  FinalsRoute: typeof FinalsRoute
  ImprintRoute: typeof ImprintRoute
  LabsRoute: typeof LabsRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProofRoute: typeof ProofRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiFarcasterCastRoute: typeof ApiFarcasterCastRoute
  ApiMarketingXPostRoute: typeof ApiMarketingXPostRoute
  ApiPredictionsHistoryRoute: typeof ApiPredictionsHistoryRoute
  ApiSocialStatusRoute: typeof ApiSocialStatusRoute
  ApiSocialVerifyRoute: typeof ApiSocialVerifyRoute
  ApiSponsorEligibilityRoute: typeof ApiSponsorEligibilityRoute
  ApiSwapPriceRoute: typeof ApiSwapPriceRoute
  ApiSwapQuoteRoute: typeof ApiSwapQuoteRoute
  ApiSwapStatusRoute: typeof ApiSwapStatusRoute
  ApiTelegramPrepareShareRoute: typeof ApiTelegramPrepareShareRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiFeedIndexRoute: typeof ApiFeedIndexRoute
  ApiAgentsCultureOpsTickRoute: typeof ApiAgentsCultureOpsTickRoute
  ApiAgentsLuckApproveRoute: typeof ApiAgentsLuckApproveRoute
  ApiAgentsLuckTickRoute: typeof ApiAgentsLuckTickRoute
  ApiAgentsPepeApproveRoute: typeof ApiAgentsPepeApproveRoute
  ApiAgentsPepeTickRoute: typeof ApiAgentsPepeTickRoute
  ApiAuthFarcasterVerifyRoute: typeof ApiAuthFarcasterVerifyRoute
  ApiAuthTelegramVerifyRoute: typeof ApiAuthTelegramVerifyRoute
  ApiAuthWorldStartRoute: typeof ApiAuthWorldStartRoute
  ApiAuthWorldVerifyRoute: typeof ApiAuthWorldVerifyRoute
  ApiAuthXCallbackRoute: typeof ApiAuthXCallbackRoute
  ApiAuthXStartRoute: typeof ApiAuthXStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finals': {
      id: '/finals'
      path: '/finals'
      fullPath: '/finals'
      preLoaderRoute: typeof FinalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defi': {
      id: '/defi'
      path: '/defi'
      fullPath: '/defi'
      preLoaderRoute: typeof DefiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed/': {
      id: '/api/feed/'
      path: '/api/feed'
      fullPath: '/api/feed/'
      preLoaderRoute: typeof ApiFeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/prepare-share': {
      id: '/api/telegram/prepare-share'
      path: '/api/telegram/prepare-share'
      fullPath: '/api/telegram/prepare-share'
      preLoaderRoute: typeof ApiTelegramPrepareShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swap/status': {
      id: '/api/swap/status'
      path: '/api/swap/status'
      fullPath: '/api/swap/status'
      preLoaderRoute: typeof ApiSwapStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swap/quote': {
      id: '/api/swap/quote'
      path: '/api/swap/quote'
      fullPath: '/api/swap/quote'
      preLoaderRoute: typeof ApiSwapQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swap/price': {
      id: '/api/swap/price'
      path: '/api/swap/price'
      fullPath: '/api/swap/price'
      preLoaderRoute: typeof ApiSwapPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sponsor/eligibility': {
      id: '/api/sponsor/eligibility'
      path: '/api/sponsor/eligibility'
      fullPath: '/api/sponsor/eligibility'
      preLoaderRoute: typeof ApiSponsorEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social/verify': {
      id: '/api/social/verify'
      path: '/api/social/verify'
      fullPath: '/api/social/verify'
      preLoaderRoute: typeof ApiSocialVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social/status': {
      id: '/api/social/status'
      path: '/api/social/status'
      fullPath: '/api/social/status'
      preLoaderRoute: typeof ApiSocialStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictions/history': {
      id: '/api/predictions/history'
      path: '/api/predictions/history'
      fullPath: '/api/predictions/history'
      preLoaderRoute: typeof ApiPredictionsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketing/x-post': {
      id: '/api/marketing/x-post'
      path: '/api/marketing/x-post'
      fullPath: '/api/marketing/x-post'
      preLoaderRoute: typeof ApiMarketingXPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/farcaster/cast': {
      id: '/api/farcaster/cast'
      path: '/api/farcaster/cast'
      fullPath: '/api/farcaster/cast'
      preLoaderRoute: typeof ApiFarcasterCastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/x/start': {
      id: '/api/auth/x/start'
      path: '/api/auth/x/start'
      fullPath: '/api/auth/x/start'
      preLoaderRoute: typeof ApiAuthXStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/x/callback': {
      id: '/api/auth/x/callback'
      path: '/api/auth/x/callback'
      fullPath: '/api/auth/x/callback'
      preLoaderRoute: typeof ApiAuthXCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/world/verify': {
      id: '/api/auth/world/verify'
      path: '/api/auth/world/verify'
      fullPath: '/api/auth/world/verify'
      preLoaderRoute: typeof ApiAuthWorldVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/world/start': {
      id: '/api/auth/world/start'
      path: '/api/auth/world/start'
      fullPath: '/api/auth/world/start'
      preLoaderRoute: typeof ApiAuthWorldStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/telegram/verify': {
      id: '/api/auth/telegram/verify'
      path: '/api/auth/telegram/verify'
      fullPath: '/api/auth/telegram/verify'
      preLoaderRoute: typeof ApiAuthTelegramVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/farcaster/verify': {
      id: '/api/auth/farcaster/verify'
      path: '/api/auth/farcaster/verify'
      fullPath: '/api/auth/farcaster/verify'
      preLoaderRoute: typeof ApiAuthFarcasterVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/pepe/tick': {
      id: '/api/agents/pepe/tick'
      path: '/api/agents/pepe/tick'
      fullPath: '/api/agents/pepe/tick'
      preLoaderRoute: typeof ApiAgentsPepeTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/pepe/approve': {
      id: '/api/agents/pepe/approve'
      path: '/api/agents/pepe/approve'
      fullPath: '/api/agents/pepe/approve'
      preLoaderRoute: typeof ApiAgentsPepeApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/luck/tick': {
      id: '/api/agents/luck/tick'
      path: '/api/agents/luck/tick'
      fullPath: '/api/agents/luck/tick'
      preLoaderRoute: typeof ApiAgentsLuckTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/luck/approve': {
      id: '/api/agents/luck/approve'
      path: '/api/agents/luck/approve'
      fullPath: '/api/agents/luck/approve'
      preLoaderRoute: typeof ApiAgentsLuckApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/culture-ops/tick': {
      id: '/api/agents/culture-ops/tick'
      path: '/api/agents/culture-ops/tick'
      fullPath: '/api/agents/culture-ops/tick'
      preLoaderRoute: typeof ApiAgentsCultureOpsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DefiRoute: DefiRoute,
  FeedRoute: FeedRoute,
  FinalsRoute: FinalsRoute,
  ImprintRoute: ImprintRoute,
  LabsRoute: LabsRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProofRoute: ProofRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiFarcasterCastRoute: ApiFarcasterCastRoute,
  ApiMarketingXPostRoute: ApiMarketingXPostRoute,
  ApiPredictionsHistoryRoute: ApiPredictionsHistoryRoute,
  ApiSocialStatusRoute: ApiSocialStatusRoute,
  ApiSocialVerifyRoute: ApiSocialVerifyRoute,
  ApiSponsorEligibilityRoute: ApiSponsorEligibilityRoute,
  ApiSwapPriceRoute: ApiSwapPriceRoute,
  ApiSwapQuoteRoute: ApiSwapQuoteRoute,
  ApiSwapStatusRoute: ApiSwapStatusRoute,
  ApiTelegramPrepareShareRoute: ApiTelegramPrepareShareRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiFeedIndexRoute: ApiFeedIndexRoute,
  ApiAgentsCultureOpsTickRoute: ApiAgentsCultureOpsTickRoute,
  ApiAgentsLuckApproveRoute: ApiAgentsLuckApproveRoute,
  ApiAgentsLuckTickRoute: ApiAgentsLuckTickRoute,
  ApiAgentsPepeApproveRoute: ApiAgentsPepeApproveRoute,
  ApiAgentsPepeTickRoute: ApiAgentsPepeTickRoute,
  ApiAuthFarcasterVerifyRoute: ApiAuthFarcasterVerifyRoute,
  ApiAuthTelegramVerifyRoute: ApiAuthTelegramVerifyRoute,
  ApiAuthWorldStartRoute: ApiAuthWorldStartRoute,
  ApiAuthWorldVerifyRoute: ApiAuthWorldVerifyRoute,
  ApiAuthXCallbackRoute: ApiAuthXCallbackRoute,
  ApiAuthXStartRoute: ApiAuthXStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
